<?php

########################################################################
# Extension Manager/Repository config file for ext: "brainmulticolumntogridelements"
#
# Auto generated by Extension Builder 2014-04-15
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Migrate Multicolumn to Gridelements',
	'description' => 'Migrates multicolumn containers to gridelements containers, since both have a different DB structure but still enough in common so this can work.
However, both extension are customizable and it is therefore impossible to make it work with every custom configuration.
USE AT YOUR OWN RISK and MAKE BACKUPS of your database.',
	'category' => 'module',
	'author' => 'Brain Appeal GmbH',
	'author_email' => 'info@brain-appeal.com',
	'author_company' => 'Brain Appeal GmbH',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '1.0.1',
	'constraints' => array(
		'depends' => array(
			'extbase' => '1.3',
			'fluid' => '1.3',
			'typo3' => '4.5.0-4.7.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>